### ISSUE TITLE
Compatibility with BMI160, BMI055, BMI085

### ISSUE THREAD

**Issue by mpkuse** [bolderflight/bmi088-arduino#1]
Hi,
First of all thanks for sharing this library. 

Do you know if this library will also work with other similar sensors from Bosch like BMI160, BMI055, BMI085 ? 

I am planning to buy one of the shuttle boards. Also do you know the exact difference, I looked at the datasheet but couldn't comprehend the difference.

**Comment by flybrianfly** [comment]
> Do you know if this library will also work with other similar sensors from Bosch like BMI160, BMI055, BMI085 ?
Likely not without at least a modification to the device ID check for the [accel](https://github.com/bolderflight/bmi088-arduino/blob/master/src/BMI088.cpp#L621) and [gyro](https://github.com/bolderflight/bmi088-arduino/blob/master/src/BMI088.cpp#L1233). Hard to say about the rest of the library without digging in to the data sheets.

The main differentiation in Bosch's product line is by application. I think their [IMU Overview](https://www.bosch-sensortec.com/products/motion-sensors/imus/) webpage includes a good description of how they see their different products.
